/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Nobu' at '16/08/26 14:46' with Gradle 2.13
 *
 * @author Nobu, @date 16/08/26 14:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
